<a href="https://colab.research.google.com/github/MynameisAbhi1910/skills-introduction-to-github/blob/main/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import tensorflow as tf
import numpy as np

In [4]:
#Creating a zero dimensional tensor
tensor_zero_d= tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
#Creating a one dimensional tensor
tensor_one_d= tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)


In [8]:
#Creating a two dimensional tensor
tensor_two_d= tf.constant([[2,0,-3],
                          [1,2,0],
                          [3,5,-1],
                          [1,5,6],
                          [2,3,8]])
print(tensor_two_d)

tf.Tensor(
[[ 2  0 -3]
 [ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(5, 3), dtype=int32)


In [9]:
#Creating a three dimensional tensor
tensor_three_d = tf.constant([[[1,2,0],[3,5,-1]],
 [[10,2,0],[1,0,2]],
  [[5,8,0],[2,7,0]],
   [[2,1,9],[4,-3,32]]])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [10]:
tensor_three_d.shape

TensorShape([4, 2, 3])

In [11]:
#Creating a four dimensional tensor
tensor_four_d= tf.constant([[[[1,2,0],[3,5,-1]],
 [[10,2,0],[1,0,2]],
  [[5,8,0],[2,7,0]],
   [[2,1,9],[4,-3,32]]],
    [[[1,2,0],[3,5,-1]],
 [[10,2,0],[1,0,2]],
  [[5,8,0],[2,7,0]],
   [[2,1,9],[4,-3,32]]],
    [[[1,2,0],[3,5,-1]],
 [[10,2,0],[1,0,2]],
  [[5,8,0],[2,7,0]],
   [[2,1,9],[4,-3,32]]]])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [13]:
#Converting numpy array to tensorflow


In [14]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [15]:
converted_tensor = tf.convert_to_tensor(np_array)

In [16]:
converted_tensor

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 4])>

In [23]:
#Making an identical tensor using eye method
eye_tensor = tf.eye(num_rows=5,
                    num_columns= None,
                    batch_shape=[2,],
                    dtype=tf.dtypes.float32,
                    name=None)
eye_tensor

<tf.Tensor: shape=(2, 5, 5), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]], dtype=float32)>

In [ ]:
#Fill method: Creates a tensor filled with a scalar value